# .goreleaser.yaml
version: 2

project_name: rdv

# Where to put build artifacts (default is dist/, but explicit is fine)
dist: dist

builds:
  - id: rdv
    main: ./cmd/rdv
    binary: rdv
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/yonasyiheyis/rdv/internal/version.Version={{ .Version }}
      - -X github.com/yonasyiheyis/rdv/internal/version.Commit={{ .ShortCommit }}
      - -X github.com/yonasyiheyis/rdv/internal/version.Date={{ .Date }}

archives:
  - id: default
    ids: [rdv]                           # replaces deprecated 'builds'
    formats: [tar.gz]                    # replaces deprecated singular 'format'
    format_overrides:                        # ← add this block
      - goos: windows
        format: zip                          # .zip for every Windows arch
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Tag }}-dev"     # replaces deprecated 'name_template'

dockers:
  # -------- linux/amd64 layer --------
  - id: linux_amd64
    image_templates:
      - ghcr.io/yonasyiheyis/rdv:{{ .Version }}-amd64
    dockerfile: ./Dockerfile
    goos: linux
    goarch: amd64
    use: buildx

  # -------- linux/arm64 layer --------
  - id: linux_arm64
    image_templates:
      - ghcr.io/yonasyiheyis/rdv:{{ .Version }}-arm64
    dockerfile: ./Dockerfile
    goos: linux
    goarch: arm64
    use: buildx

docker_manifests:
  # version tag
  - name_template: ghcr.io/yonasyiheyis/rdv:{{ .Version }}
    image_templates:
      - ghcr.io/yonasyiheyis/rdv:{{ .Version }}-amd64
      - ghcr.io/yonasyiheyis/rdv:{{ .Version }}-arm64
  # latest tag
  - name_template: ghcr.io/yonasyiheyis/rdv:latest
    image_templates:
      - ghcr.io/yonasyiheyis/rdv:{{ .Version }}-amd64
      - ghcr.io/yonasyiheyis/rdv:{{ .Version }}-arm64

brews:
  - repository:
      owner: yonasyiheyis
      name: homebrew-rdv
      token: "{{ .Env.HOMEBREW_GITHUB_API_TOKEN }}"
    name: rdv
    description: "Interactive dev‑env config manager"
    homepage: "https://github.com/yonasyiheyis/rdv"
    caveats: |
      After installation, enable shell completion:
        rdv completion zsh > $(brew --prefix)/share/zsh/site-functions/_rdv
    test: |
      rdv --version

# --- SBOMs: generate SPDX JSON for release archives ---
sboms:
  - id: sbom-archives
    artifacts: archive
    documents:
      - "{{ .ArtifactName }}.spdx.json"

# --- Sign non-docker artifacts (checksums and archives) with cosign keyless ---
signs:
  - id: sign-checksum
    cmd: cosign
    artifacts: checksum
    args:
      - sign-blob
      - --yes
      - --output-signature=${signature}
      - --output-certificate=${certificate}
      - ${artifact}

  - id: sign-archives
    cmd: cosign
    artifacts: archive
    args:
      - sign-blob
      - --yes
      - --output-signature=${signature}
      - --output-certificate=${certificate}
      - ${artifact}

# --- Sign docker images pushed by GoReleaser (GHCR) with cosign keyless ---
docker_signs:
  - id: sign-images
    cmd: cosign
    args:
      - sign
      - --yes
      - ${artifact}