# .goreleaser.yaml
version: 2

project_name: rdv

# Where to put build artifacts (default is dist/, but explicit is fine)
dist: dist

builds:
  - id: rdv
    main: ./cmd/rdv
    binary: rdv
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/yonasyiheyis/rdv/internal/version.Version={{ .Version }}
      - -X github.com/yonasyiheyis/rdv/internal/version.Commit={{ .ShortCommit }}
      - -X github.com/yonasyiheyis/rdv/internal/version.Date={{ .Date }}

archives:
  - id: default
    ids: [rdv]                           # replaces deprecated 'builds'
    formats: [tar.gz]                    # replaces deprecated singular 'format'
    format_overrides:                        # ← add this block
      - goos: windows
        format: zip                          # .zip for every Windows arch
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ .Tag }}-dev"     # replaces deprecated 'name_template'

# No publishing/announcing config yet; we'll add later when ready

brews:
  - repository:
      owner: yonasyiheyis
      name: homebrew-rdv
      token: "{{ .Env.HOMEBREW_GITHUB_API_TOKEN }}"
    name: rdv
    description: "Interactive dev‑env config manager"
    homepage: "https://github.com/yonasyiheyis/rdv"
    caveats: |
      After installation, enable shell completion:
        rdv completion zsh > $(brew --prefix)/share/zsh/site-functions/_rdv
    test: |
      rdv --version